//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesWithAuth
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieUser
    {
        public int MovieId { get; set; }
        public string UserName { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
